-- MySQL Script generated by MySQL Workbench
-- Sat Jul 15 18:39:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auto_repair_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auto_repair_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auto_repair_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `auto_repair_shop` ;

-- -----------------------------------------------------
-- Table `auto_repair_shop`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_address` VARCHAR(255) NOT NULL,
  `customer_phone_number` VARCHAR(20) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(255) NOT NULL,
  `employee_address` VARCHAR(255) NOT NULL,
  `employee_phone_number` VARCHAR(20) NOT NULL,
  `employee_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`vehicle` (
  `vehicle_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `make` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `vin` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`vehicle_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `vehicle_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `auto_repair_shop`.`customer` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`service` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`work_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`work_order` (
  `work_order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`work_order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  INDEX `service_id` (`service_id` ASC) VISIBLE,
  CONSTRAINT `work_order_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `auto_repair_shop`.`customer` (`customer_id`),
  CONSTRAINT `work_order_ibfk_2`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `auto_repair_shop`.`vehicle` (`vehicle_id`),
  CONSTRAINT `work_order_ibfk_3`
    FOREIGN KEY (`service_id`)
    REFERENCES `auto_repair_shop`.`service` (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`employee_work_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`employee_work_order` (
  `employee_id` INT NOT NULL,
  `work_order_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `work_order_id`),
  INDEX `work_order_id` (`work_order_id` ASC) VISIBLE,
  CONSTRAINT `employee_work_order_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `auto_repair_shop`.`employee` (`employee_id`),
  CONSTRAINT `employee_work_order_ibfk_2`
    FOREIGN KEY (`work_order_id`)
    REFERENCES `auto_repair_shop`.`work_order` (`work_order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(255) NOT NULL,
  `supplier_address` VARCHAR(255) NOT NULL,
  `supplier_phone_number` VARCHAR(20) NOT NULL,
  `supplier_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`part` (
  `part_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `manufacturer` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `supplier_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`part_id`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `part_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `auto_repair_shop`.`supplier` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`inventory` (
  `inventory_id` INT NOT NULL AUTO_INCREMENT,
  `part_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `part_id` (`part_id` ASC) VISIBLE,
  CONSTRAINT `inventory_ibfk_1`
    FOREIGN KEY (`part_id`)
    REFERENCES `auto_repair_shop`.`part` (`part_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auto_repair_shop`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_repair_shop`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `work_order_id` INT NOT NULL,
  `invoice_date` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `work_order_id` (`work_order_id` ASC) VISIBLE,
  CONSTRAINT `invoice_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `auto_repair_shop`.`customer` (`customer_id`),
  CONSTRAINT `invoice_ibfk_2`
    FOREIGN KEY (`work_order_id`)
    REFERENCES `auto_repair_shop`.`work_order` (`work_order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
